DROP TABLE IF EXISTS OLYMPICS_HISTORY_NOC_REGIONS;
CREATE TABLE IF NOT EXISTS OLYMPICS_HISTORY_NOC_REGIONS
(
NOC VARCHAR,
REGION VARCHAR,
NOTES VARCHAR
);


SELECT * FROM OLYMPICS_HISTORY;
1. find total no of olympic games
(select distinct from )
SELECT * FROM OLYMPICS_HISTORY_NOC_REGIONS;




with t1 
as (SELECT NAME,COUNT(1) as total_medals
FROM OLYMPICS_HISTORY
WHERE medals='gold'
group by name
order by count(1),